---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 5-demo-helm-release-git-helm-bb-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: block-buster-helm-app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 5-demo-source-git-helm-bb-app
  interval: 10s
  targetNamespace: 5-demo
  values:
    - path: ./5-demo-values.yaml

